In [1]:
import torch
import torch.nn as nn
from ae_lstm import *

In [2]:
x = torch.rand(3, 4, 24)
x = x.transpose(1, 2)
x.shape

torch.Size([3, 24, 4])

In [3]:
model = AutoEncoderLSTM_expo(10, 4)
model

AutoEncoderLSTM_expo(
  (encoder): Encoder(
    (lstm): LSTM(4, 10, batch_first=True)
  )
  (decoder): Decoder(
    (lstm): LSTM(10, 10, batch_first=True)
  )
  (linear): Linear(in_features=10, out_features=4, bias=True)
)

In [4]:
output = model(x)
output

tensor([[[-0.2081, -0.3142,  0.3010,  0.2235],
         [-0.2149, -0.3203,  0.3147,  0.2032],
         [-0.2227, -0.3202,  0.3208,  0.1927],
         [-0.2292, -0.3181,  0.3234,  0.1871],
         [-0.2340, -0.3159,  0.3244,  0.1841],
         [-0.2375, -0.3141,  0.3248,  0.1824],
         [-0.2399, -0.3126,  0.3249,  0.1813],
         [-0.2416, -0.3115,  0.3249,  0.1807],
         [-0.2428, -0.3107,  0.3249,  0.1803],
         [-0.2436, -0.3102,  0.3249,  0.1800],
         [-0.2442, -0.3098,  0.3249,  0.1799],
         [-0.2446, -0.3096,  0.3249,  0.1797],
         [-0.2449, -0.3094,  0.3250,  0.1797],
         [-0.2451, -0.3092,  0.3250,  0.1796],
         [-0.2452, -0.3092,  0.3250,  0.1796],
         [-0.2453, -0.3091,  0.3250,  0.1795],
         [-0.2454, -0.3091,  0.3250,  0.1795],
         [-0.2454, -0.3090,  0.3250,  0.1795],
         [-0.2455, -0.3090,  0.3250,  0.1795],
         [-0.2455, -0.3090,  0.3250,  0.1795],
         [-0.2455, -0.3090,  0.3250,  0.1795],
         [-0.

In [5]:
output.shape

torch.Size([3, 24, 4])

In [6]:
layers = list(model.children())
encoder = nn.Sequential(layers[0]) 
encoder

Sequential(
  (0): Encoder(
    (lstm): LSTM(4, 10, batch_first=True)
  )
)

In [7]:
encoder(x).squeeze(0).shape

torch.Size([3, 10])

In [8]:
import json
t = {'ss':'gg'}
with open('test.txt', 'w') as f:
    json.dump(t, f)

In [9]:
import numpy as np
p = np.random.rand(4, 6)
p

array([[0.22627803, 0.81023407, 0.50449919, 0.26938748, 0.0544748 ,
        0.26059659],
       [0.54880029, 0.14439089, 0.01130292, 0.4615891 , 0.72587865,
        0.22624136],
       [0.68845251, 0.10216888, 0.99285929, 0.57046318, 0.17137779,
        0.91079214],
       [0.14069701, 0.87556724, 0.17181154, 0.21009784, 0.71492542,
        0.75390937]])

In [10]:
p.reshape((2, 3, 4))


array([[[0.22627803, 0.81023407, 0.50449919, 0.26938748],
        [0.0544748 , 0.26059659, 0.54880029, 0.14439089],
        [0.01130292, 0.4615891 , 0.72587865, 0.22624136]],

       [[0.68845251, 0.10216888, 0.99285929, 0.57046318],
        [0.17137779, 0.91079214, 0.14069701, 0.87556724],
        [0.17181154, 0.21009784, 0.71492542, 0.75390937]]])

In [11]:
torch.utils.data.Dataset(x)

TypeError: object() takes no parameters