In [1]:
import torch
import torch.nn as nn
from ae_lstm import *

In [2]:
x = torch.rand(3, 4, 24)
x = x.transpose(1, 2)
x.shape

torch.Size([3, 24, 4])

In [3]:
model = AutoEncoderLSTM(10, 4)
model

AutoEncoderLSTM(
  (encoder): Encoder(
    (lstm): LSTM(4, 10, batch_first=True)
  )
  (decoder): Decoder(
    (lstm): LSTM(10, 10, batch_first=True)
  )
  (linear): Linear(in_features=10, out_features=4, bias=True)
)

In [4]:
output = model(x)
output

torch.Size([3, 24, 10])
torch.Size([3, 1, 10])


tensor([[[-0.0288,  0.2544,  0.3381, -0.1239],
         [-0.0288,  0.2544,  0.3380, -0.1239],
         [-0.0288,  0.2544,  0.3380, -0.1239],
         [-0.0288,  0.2544,  0.3380, -0.1239],
         [-0.0288,  0.2544,  0.3380, -0.1239],
         [-0.0288,  0.2544,  0.3380, -0.1239],
         [-0.0288,  0.2543,  0.3379, -0.1239],
         [-0.0288,  0.2543,  0.3378, -0.1239],
         [-0.0288,  0.2542,  0.3377, -0.1239],
         [-0.0288,  0.2541,  0.3376, -0.1238],
         [-0.0288,  0.2540,  0.3374, -0.1238],
         [-0.0289,  0.2538,  0.3372, -0.1238],
         [-0.0289,  0.2535,  0.3368, -0.1238],
         [-0.0290,  0.2531,  0.3362, -0.1238],
         [-0.0290,  0.2526,  0.3355, -0.1237],
         [-0.0291,  0.2519,  0.3344, -0.1237],
         [-0.0293,  0.2509,  0.3328, -0.1237],
         [-0.0295,  0.2496,  0.3306, -0.1236],
         [-0.0300,  0.2479,  0.3273, -0.1235],
         [-0.0309,  0.2457,  0.3227, -0.1232],
         [-0.0328,  0.2430,  0.3162, -0.1223],
         [-0.

In [5]:
output.shape

torch.Size([3, 24, 4])

In [6]:
layers = list(model.children())
encoder = nn.Sequential(layers[0]) 
encoder

Sequential(
  (0): Encoder(
    (lstm): LSTM(4, 10, batch_first=True)
  )
)

In [13]:
encoder(x).squeeze(0).shape

torch.Size([3, 10])

In [8]:
import json
t = {'ss':'gg'}
with open('test.txt', 'w') as f:
    json.dump(t, f)

In [9]:
import numpy as np
p = np.random.rand(4, 6)
p

array([[0.70049838, 0.15116283, 0.53720804, 0.58765814, 0.07152135,
        0.55210337],
       [0.88633974, 0.87347717, 0.71500646, 0.50297395, 0.60584101,
        0.92290444],
       [0.85619012, 0.84202522, 0.48023314, 0.1087635 , 0.39778133,
        0.70395983],
       [0.00762988, 0.13266029, 0.37945514, 0.11621597, 0.40571925,
        0.01548308]])

In [10]:
p.reshape((2, 3, 4))


array([[[0.70049838, 0.15116283, 0.53720804, 0.58765814],
        [0.07152135, 0.55210337, 0.88633974, 0.87347717],
        [0.71500646, 0.50297395, 0.60584101, 0.92290444]],

       [[0.85619012, 0.84202522, 0.48023314, 0.1087635 ],
        [0.39778133, 0.70395983, 0.00762988, 0.13266029],
        [0.37945514, 0.11621597, 0.40571925, 0.01548308]]])

In [11]:
torch.utils.data.Dataset(x)

TypeError: object() takes no parameters