In [1]:
import torch
import torch.nn as nn
from ae_tcn import *

In [2]:
x = torch.rand(2, 4, 24)
x

tensor([[[0.2409, 0.3914, 0.8919, 0.1811, 0.2092, 0.5130, 0.5842, 0.7224,
          0.0950, 0.0856, 0.4203, 0.5684, 0.6873, 0.5449, 0.8076, 0.5188,
          0.4465, 0.5085, 0.7235, 0.1270, 0.6352, 0.6771, 0.6598, 0.6555],
         [0.5316, 0.2575, 0.7264, 0.8344, 0.4696, 0.9487, 0.0181, 0.5086,
          0.6404, 0.2371, 0.5982, 0.3019, 0.1573, 0.1711, 0.6184, 0.9259,
          0.7415, 0.6890, 0.6159, 0.9564, 0.8840, 0.0510, 0.1352, 0.2129],
         [0.9042, 0.9917, 0.9441, 0.2805, 0.4529, 0.8412, 0.4776, 0.8667,
          0.0358, 0.9381, 0.4363, 0.6755, 0.5514, 0.8020, 0.8033, 0.3901,
          0.5462, 0.1862, 0.1042, 0.9036, 0.8585, 0.7799, 0.7164, 0.5898],
         [0.0015, 0.5969, 0.8002, 0.9407, 0.6556, 0.3587, 0.1240, 0.0203,
          0.5769, 0.8292, 0.5953, 0.4922, 0.1412, 0.2646, 0.8616, 0.9211,
          0.1412, 0.4923, 0.7095, 0.8550, 0.6798, 0.9167, 0.7529, 0.0922]],

        [[0.2497, 0.4857, 0.6459, 0.1065, 0.9966, 0.2404, 0.5369, 0.3606,
          0.3124, 0.5176, 0.4275

In [3]:
model = AutoEncoderTCN()
model

AutoEncoderTCN(
  (ae_tcn): Sequential(
    (0): TCNEncoder(
      (encoder): Sequential(
        (0): DilationTCN(
          (network): Sequential(
            (0): TCNBlock(
              (tcn): Sequential(
                (0): Conv1d(4, 10, kernel_size=(2,), stride=(1,), padding=(1,))
                (1): Chomp1d()
                (2): LeakyReLU(negative_slope=0.01)
                (3): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(1,))
                (4): Chomp1d()
                (5): LeakyReLU(negative_slope=0.01)
              )
              (up_down_sampling): Conv1d(4, 10, kernel_size=(1,), stride=(1,))
            )
            (1): TCNBlock(
              (tcn): Sequential(
                (0): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
                (1): Chomp1d()
                (2): LeakyReLU(negative_slope=0.01)
                (3): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
                (4):

In [4]:
output = model(x)
output

tensor([[[ 0.2542,  0.0313,  0.1553,  0.0526,  0.1074,  0.4127,  0.3191,
           0.2708,  0.1705, -0.0403,  0.3062,  0.0042, -0.2564,  0.2979,
          -0.0073,  0.3526, -0.0497,  0.0717,  0.1713, -0.0088,  0.0354,
          -0.2139,  0.0063,  0.3146],
         [ 0.3710,  0.1377,  0.5509,  0.0360,  0.4124,  0.1864,  0.5437,
           0.2115,  0.4536,  0.3948,  0.6532,  0.4352,  0.1381,  0.2033,
           0.5417,  0.4387,  0.4333,  0.4483,  0.4827,  0.3000,  0.6074,
           0.3257,  0.6334,  0.1754],
         [-0.2128, -0.0371,  0.0245, -0.0096,  0.0050, -0.4473, -0.1503,
          -0.2087, -0.0417,  0.2390, -0.0815,  0.1627,  0.3910, -0.3273,
           0.2548, -0.1766,  0.2712,  0.1819, -0.0115,  0.1164,  0.1833,
           0.4547,  0.2424, -0.3410],
         [ 0.1798, -0.0573, -0.1252, -0.1930, -0.1409,  0.1888,  0.0408,
           0.0860, -0.0083, -0.2203,  0.1245, -0.0920, -0.4284,  0.0860,
          -0.3533,  0.0807, -0.2950, -0.1945, -0.0346, -0.0726, -0.1759,
          

In [5]:
output.shape

torch.Size([2, 4, 24])

In [9]:
layers = list(model.ae_tcn.children())
encoder = nn.Sequential(*layers[:-1]) 
encoder

Sequential(
  (0): TCNEncoder(
    (encoder): Sequential(
      (0): DilationTCN(
        (network): Sequential(
          (0): TCNBlock(
            (tcn): Sequential(
              (0): Conv1d(4, 10, kernel_size=(2,), stride=(1,), padding=(1,))
              (1): Chomp1d()
              (2): LeakyReLU(negative_slope=0.01)
              (3): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(1,))
              (4): Chomp1d()
              (5): LeakyReLU(negative_slope=0.01)
            )
            (up_down_sampling): Conv1d(4, 10, kernel_size=(1,), stride=(1,))
            (relu): LeakyReLU(negative_slope=0.01)
          )
          (1): TCNBlock(
            (tcn): Sequential(
              (0): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
              (1): Chomp1d()
              (2): LeakyReLU(negative_slope=0.01)
              (3): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
              (4): Chomp1d()
          

In [14]:
encoder(x).shape

torch.Size([2, 1, 5])

In [4]:
import json
t = {'ss':'gg'}
with open('test.txt', 'w') as f:
    json.dump(t, f)

In [7]:
import numpy as np
p = np.random.rand(4, 6)
p

array([[0.0662918 , 0.21491427, 0.24592332, 0.83223128, 0.55519726,
        0.92635879],
       [0.30298795, 0.74151675, 0.11780557, 0.88411639, 0.92238706,
        0.11445098],
       [0.95803676, 0.0744373 , 0.73087636, 0.6552559 , 0.27092587,
        0.55949527],
       [0.64071354, 0.74512438, 0.74691057, 0.71991843, 0.49381706,
        0.64234496]])

In [11]:
p.reshape((2, 3, 4))


array([[[0.0662918 , 0.21491427, 0.24592332, 0.83223128],
        [0.55519726, 0.92635879, 0.30298795, 0.74151675],
        [0.11780557, 0.88411639, 0.92238706, 0.11445098]],

       [[0.95803676, 0.0744373 , 0.73087636, 0.6552559 ],
        [0.27092587, 0.55949527, 0.64071354, 0.74512438],
        [0.74691057, 0.71991843, 0.49381706, 0.64234496]]])

In [21]:
torch.utils.data.Dataset(x)

TypeError: object() takes no parameters