In [1]:
import torch
import torch.nn as nn
from ae_tcn import *

In [2]:
x = torch.rand(2, 4, 24)
x

tensor([[[0.6805, 0.4355, 0.1601, 0.7652, 0.8565, 0.3488, 0.1584, 0.4761,
          0.7181, 0.0932, 0.1159, 0.2489, 0.8041, 0.2414, 0.7562, 0.3716,
          0.2802, 0.0372, 0.4501, 0.0606, 0.1389, 0.9370, 0.2124, 0.6328],
         [0.8038, 0.0729, 0.2177, 0.3249, 0.4134, 0.7588, 0.5773, 0.8983,
          0.0957, 0.9978, 0.3815, 0.5511, 0.9562, 0.9330, 0.8224, 0.4812,
          0.1976, 0.2948, 0.4169, 0.2675, 0.0864, 0.0370, 0.2862, 0.0253],
         [0.7673, 0.2127, 0.6317, 0.2725, 0.4775, 0.9757, 0.9309, 0.5292,
          0.1552, 0.3893, 0.8793, 0.8935, 0.0185, 0.6888, 0.9355, 0.9128,
          0.4731, 0.3850, 0.1378, 0.9346, 0.2556, 0.5309, 0.9798, 0.1093],
         [0.0741, 0.3762, 0.2206, 0.1271, 0.3706, 0.4812, 0.6546, 0.2219,
          0.4835, 0.3823, 0.1408, 0.8111, 0.5935, 0.6955, 0.0619, 0.8651,
          0.5197, 0.7749, 0.8592, 0.7043, 0.2869, 0.9421, 0.5821, 0.8974]],

        [[0.2848, 0.7052, 0.1206, 0.7866, 0.6299, 0.8323, 0.4913, 0.7886,
          0.0530, 0.8101, 0.8941

In [3]:
model = AutoEncoderTCN()
model

AutoEncoderTCN(
  (ae_tcn): Sequential(
    (0): TCNEncoder(
      (encoder): Sequential(
        (0): DilationTCN(
          (network): Sequential(
            (0): TCNBlock(
              (tcn): Sequential(
                (0): Conv1d(4, 10, kernel_size=(2,), stride=(1,), padding=(1,))
                (1): Chomp1d()
                (2): LeakyReLU(negative_slope=0.01)
                (3): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(1,))
                (4): Chomp1d()
                (5): LeakyReLU(negative_slope=0.01)
              )
              (up_down_sampling): Conv1d(4, 10, kernel_size=(1,), stride=(1,))
            )
            (1): TCNBlock(
              (tcn): Sequential(
                (0): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
                (1): Chomp1d()
                (2): LeakyReLU(negative_slope=0.01)
                (3): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
                (4):

In [4]:
output = model(x)
output

tensor([[[-0.3130, -0.3578, -0.7423, -0.8806, -0.3607, -0.2936, -0.5474,
           0.1537, -0.8583, -0.5082, -0.6662, -0.0858, -0.8550, -0.2110,
          -0.4032, -0.4400, -0.4336, -0.0521, -0.5036, -0.1672, -0.1428,
          -0.8485, -0.8464, -0.7903],
         [ 0.1081,  0.1183,  0.0728,  0.2008,  0.3055,  0.2358,  0.0731,
           0.1708,  0.0210,  0.1992,  0.2137,  0.3912,  0.0595,  0.2823,
           0.1375,  0.0927,  0.1827,  0.2661,  0.0262,  0.0551,  0.1415,
           0.0332,  0.1571,  0.3562],
         [-0.2441, -0.1981, -0.0371,  0.0706, -0.2684, -0.3085, -0.1168,
          -0.5435,  0.0072, -0.1271, -0.1725, -0.4377, -0.0124, -0.2705,
          -0.2401, -0.2981, -0.1781, -0.4050, -0.1585, -0.3708, -0.3607,
           0.0165,  0.0315, -0.1553],
         [ 0.2451,  0.3551,  0.7569,  1.0154,  0.3412,  0.2464,  0.5768,
          -0.4039,  0.8433,  0.6498,  0.5396, -0.0327,  0.8621,  0.0906,
           0.3351,  0.1983,  0.2815, -0.0903,  0.3265, -0.0238,  0.1950,
          

In [5]:
output.shape

torch.Size([2, 4, 24])

In [9]:
layers = list(model.ae_tcn.children())
encoder = nn.Sequential(*layers[:-1]) 
encoder

Sequential(
  (0): TCNEncoder(
    (encoder): Sequential(
      (0): DilationTCN(
        (network): Sequential(
          (0): TCNBlock(
            (tcn): Sequential(
              (0): Conv1d(4, 10, kernel_size=(2,), stride=(1,), padding=(1,))
              (1): Chomp1d()
              (2): LeakyReLU(negative_slope=0.01)
              (3): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(1,))
              (4): Chomp1d()
              (5): LeakyReLU(negative_slope=0.01)
            )
            (up_down_sampling): Conv1d(4, 10, kernel_size=(1,), stride=(1,))
            (relu): LeakyReLU(negative_slope=0.01)
          )
          (1): TCNBlock(
            (tcn): Sequential(
              (0): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
              (1): Chomp1d()
              (2): LeakyReLU(negative_slope=0.01)
              (3): Conv1d(10, 10, kernel_size=(2,), stride=(1,), padding=(2,), dilation=(2,))
              (4): Chomp1d()
          

In [14]:
encoder(x).shape

torch.Size([2, 1, 5])

In [4]:
import json
t = {'ss':'gg'}
with open('test.txt', 'w') as f:
    json.dump(t, f)

In [7]:
import numpy as np
p = np.random.rand(4, 6)
p

array([[0.0662918 , 0.21491427, 0.24592332, 0.83223128, 0.55519726,
        0.92635879],
       [0.30298795, 0.74151675, 0.11780557, 0.88411639, 0.92238706,
        0.11445098],
       [0.95803676, 0.0744373 , 0.73087636, 0.6552559 , 0.27092587,
        0.55949527],
       [0.64071354, 0.74512438, 0.74691057, 0.71991843, 0.49381706,
        0.64234496]])

In [11]:
p.reshape((2, 3, 4))


array([[[0.0662918 , 0.21491427, 0.24592332, 0.83223128],
        [0.55519726, 0.92635879, 0.30298795, 0.74151675],
        [0.11780557, 0.88411639, 0.92238706, 0.11445098]],

       [[0.95803676, 0.0744373 , 0.73087636, 0.6552559 ],
        [0.27092587, 0.55949527, 0.64071354, 0.74512438],
        [0.74691057, 0.71991843, 0.49381706, 0.64234496]]])

In [21]:
torch.utils.data.Dataset(x)

TypeError: object() takes no parameters